{% extends "layout.phtml" %}
{% block mainbody %}

		<div class="maintitle"><h1>Recipe Feed</h1></div>
		<div class="separator">&nbsp;</div>
			<ul class="recipeList"></ul>
			
			

<div id="Searchresult">

This content will be replaced when pagination inits.
</div>
<div id="Pagination"></div>
        
         <!-- Container element for all the Elements that are to be paginated -->
        <div id="hiddenresult" style="display:none;">
        	<div class="result">Testing 1</div>
        	<div class="result">Testing 2</div>
        	<div class="result">Testing 3</div>
        </div>



		</div>

{% endblock %}
